export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_ERROR = 'RESET_PASSWORD_REQUEST_ERROR';
export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const VALIDATE_TOKEN_ERROR = 'VALIDATE_TOKEN_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const FETCH_BUSINESSES = 'FETCH_BUSINESSES';
export const FETCH_BUSINESSES_ERROR = 'FETCH_BUSINESSES_ERROR';

export const VOTE_LIKE = 'VOTE_LIKE';
export const UPDATE_VOTE_LIKE = 'UPDATE_VOTE_LIKE';
export const VOTE_UNLIKE = 'VOTE_UNLIKE';
export const GET_VOTES = 'GET_VOTES';